### PR TITLE
Create getexamples.py

### PR DESCRIPTION
**Pull request by Jeremy-Harper**
This is code that iterates through a list of complex topics and then creates a question and then responds to that question. It then grades that response and if acceptable it outputs it to a new JSON file. I've setup and tested on LM studio, it uses standard openai API's

### CODE REVIEW

**Comment by daveshap** [comment]
Please review the contributing documentation before submitting PRs.

**Comment by Jeremy-Harper** [comment]
You realize this automated your entire task? Doing it manually like you did on video was time consuming. I tested it locally with success. Also it met what’s been put in the contributing documentation on the repo. Maybe you meant to put something else? On Sep 14, 2024, at 3:12 PM, David Shapiro ***@***.***> wrote:﻿
Please review the contributing documentation before submitting PRs.

**Comment by russellballestrini** [comment]
My suggestion is to keep it in your fork until we are ready to pick an approach. Thank you for finding an automated way, this is similar to how I would do it.

I would consider using Hermes 3.1 XML for my chain of thoughts instead of JSON ect because that way we can fine tune a fine tune that already has the chains built-in.

No clue of this fits but it's what I'm doing in my repo and research.

**Comment by daveshap** [comment]
@Jeremy-Harper 

> This is being built in public due to our open source ethos by a closed team. However, if you spot something please open an ISSUE before submitting a PR.

You did not review the contributing documentation.

**Pull request closed without merging**
